name: jrnd
base: core22
version: 0.3.9
summary: Random data generator
description: |
  Command line generator of random data.

grade: stable
confinement: strict

apps:
  jr:
    command: bin/jr
    environment:
      JR_SYSTEM_DIR: $SNAP
    plugs:
      - home

parts:
  jr:
    plugin: make
    source-type: git
    source-tag: v0.3.9
    source: https://github.com/jrnd-io/jr
    build-snaps: [go/1.22/stable]
    disable-parallel: true
    override-build: |-
      make
      sed -i 's|USER=$(shell id -u -n)|USER=snapcraft|g' Makefile
      make all
      install -DT "./build/jr" "$SNAPCRAFT_PART_INSTALL/bin/jr"

  jr-copy-files-templates:
    plugin: dump
    source-type: git
    source-tag: v0.3.9
    source: https://github.com/jrnd-io/jr
    source-subdir: "templates"
    organize:
      "*": templates/

  jr-copy-files-config:
    plugin: dump
    source-type: git
    source-tag: v0.3.9
    source: https://github.com/jrnd-io/jr
    source-subdir: "config"
