# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-linux-release

on:
  push:
    tags:
      - "v*"

jobs:

  build:
    name: "Tagged release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.3
    - name: Install dependencies
      run: go get .
    - name: Run build script
      run: ./make_install.sh
      shell: bash

    - name: release
      id: create_release
      uses: actions/create-release@v1
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }} linux amd64
        tag_name: ${{ github.ref }}
        body_path: ReleaseNotes.txt

    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/jr
        asset_name: jr
        asset_content_type: application/bin