name: snap

on:
  workflow_dispatch:
  push:
    paths:
      - "snap/snapcraft.yaml"

jobs:
  snapcraft:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
        id: build
      - uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable
